### PR TITLE
Statically compile linux binaries, and try to fix OS X binaries

### LINKED ISSUE #826: Signing issues on OSX
Due to https://github.com/golang/go/issues/11887 the notary binary, when signed, will not run on OSX. We currently workaround the issue by rebuilding the application with striped dwarf symbols:

https://github.com/djs55/notary/commit/31e4b19260d57f0f59b596bb38aa4a6d5075be1a

Would be great to have a proper solution integrated upstream.

/cc @justincormack and @djs55

### PR DESCRIPTION
**Pull request by cyli**
Modify the cross-compile script to statically compile the linux binary (which includes libtool).

This hopefully compiles the OS X binary in such a way as to address #826.

### CODE REVIEW

File: buildscripts/cross.sh [hunk 1]
```diff
@@ -15,19 +20,23 @@ for os in "$@"; do
 	if [[ "${GOOS}" == "darwin" ]]; then
 		export CC="o64-clang"
 		export CXX="o64-clang++"
-		# -ldflags=-s:  see https://github.com/golang/go/issues/11994
-		export LDFLAGS="${GO_LDFLAGS} -ldflags=-s"
+		# -ldflags=-s:  see https://github.com/golang/go/issues/11994 - TODO: this has been fixed in go 1.7.1
```
Comment (riyazdf) [inline buildscripts/cross.sh]: Not sure if I understand if this is fixed by #943?  Do we still need `LDFLAGS="-s"`?

Comment (cyli) [inline buildscripts/cross.sh]: It could be - I'd need to verify with @justincormack.

**Comment by cyli** [comment]
Ok, checked with @justincormack, and the mac binary generated with `make cross` seems to be signable, so this should be able to produce release binaries that would work.

**Comment by riyazdf** [comment]
Gave this a spin and worked great!  LGTM

File: buildscripts/cross.sh (hunk 1 above)
Comment (justincormack) [inline buildscripts/cross.sh]: Seems to be fine without with 1.7.1

**Comment by endophage** [comment]
I'm as uncertain on this as everyone else but it looks right based on everything else I've seen. LGTM

**Comment by endophage** [comment]
One question before merging, would it obsolete the need for this change if we updated to Go 1.7.1? (and is that easy to do?)

**Comment by cyli** [comment]
@endophage not all of this change, because this change involves passing the extra static and CTIME flags which we didn't correctly do the last time.  But it would obsolete the `-s` part, and yes that is easy to do
