### PR TITLE
fixing Sha256 capitalization per Go rules on acronyms

### LINKED ISSUE #1024: Fix `Sha256` naming
"SHA" is an acronym so following Go's coding standards should either be `sha` or `SHA` depending on whether it needs to be exported or not. `github.com/server/storage.TUFFile` at least has the naming wrong, a case sensitive grep may find other places.

### PR DESCRIPTION
**Pull request by endophage**
Closes #1024 

Signed-off-by: David Lawrence <david.lawrence@docker.com> (github: endophage)

### CODE REVIEW

File: server/storage/sql_models.go [hunk 1]
```diff
@@ -17,7 +17,7 @@ type TUFFile struct {
 	Gun     string `sql:"type:varchar(255);not null"`
 	Role    string `sql:"type:varchar(255);not null"`
 	Version int    `sql:"not null"`
-	Sha256  string `sql:"type:varchar(64);"`
+	SHA256  string `gorm:"column:sha256" sql:"type:varchar(64);"`
```
Comment (riyazdf) [inline server/storage/sql_models.go]: any reason to add this to the model?

Comment (endophage) [inline server/storage/sql_models.go]: `s_h_a256` :-P

gorm splits on capital letters

Comment (riyazdf) [inline server/storage/sql_models.go]: aha!  Good to know :)
