### PR TITLE
Validate root rotations against trust pinning where appropriate

### LINKED ISSUE #735: Validate new root cert against trust pinning
When a new root cert is being rotated in, validate that is passes the current trust pinning. This will help ensure the currently available trust pinning information is correct and new users will be able to trust the new root key.

If it fails to validate. Fail the rotation with an message that makes it obvious what the issue is.

### PR DESCRIPTION
**Pull request by riyazdf**
Check new roots against the trust pinning when performing validation, but do not reject the new root if TOFUs is disabled because we've already trusted a previous root.
 
Closes #735.

Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>

### CODE REVIEW

File: trustpinning/trustpin.go [hunk 1]
```diff
@@ -62,6 +62,14 @@ func NewTrustPinChecker(trustPinConfig TrustPinConfig, gun string) (CertChecker,
 	if !trustPinConfig.DisableTOFU {
 		return t.tofusCheck, nil
 	}
+
+	// If we already have previous trusted root data for this GUN, disabling TOFUs should not change trust
+	// At this point, we assume that we have already trusted previous root data and so will not perform any
+	// additional trust pinning checks on this new certificate
+	if !firstBootstrap {
+		logrus.Debug("TOFU is disabled but previous root data exists, skipping disable TOFU restriction")
```
Comment (cyli) [inline trustpinning/trustpin.go]: Nit:  I'm wondering if this log message might be confusing, since it's not exactly doing a TOFU check, since it's not first use.  It's just that no other trust pinning has been specified.  In which case maybe this check can just be combined with the previous conditional?

File: trustpinning/certs_test.go [hunk 2]
```diff
@@ -781,6 +781,200 @@ func testValidateRootRotationMissingNewSig(t *testing.T, keyAlg, rootKeyType str
...
+
+	// Even if we disable TOFU in the trustpinning, since we have a previously trusted root we should honor a valid rotation
+	validatedRoot, err = trustpinning.ValidateRoot(prevRoot, signedTestRoot, gun, trustpinning.TrustPinConfig{DisableTOFU: true})
+	require.NoError(t, err)
+	generateRootKeyIDs(typedSignedRoot)
+	require.Equal(t, typedSignedRoot, validatedRoot)
+}
+
+// TestValidateRootRotationTrustPinningInvalidCA runs a full root certificate rotation but ensures that
+// the specified trust pinning rejectas the new root for not being signed by the specified CA
```
Comment (cyli) [inline trustpinning/certs_test.go]: Nitpick:  "rejects"

File: trustpinning/certs_test.go [hunk 3]
```diff
@@ -781,6 +781,200 @@ func testValidateRootRotationMissingNewSig(t *testing.T, keyAlg, rootKeyType str
...
+			data.CanonicalTargetsRole:   &rootRole.RootRole,
+			data.CanonicalSnapshotRole:  &rootRole.RootRole},
+		false,
+	)
+	testRoot.Signed.Version = 1
+	require.NoError(t, err, "Failed to create new root")
+
+	keyReader, err := os.Open("../fixtures/notary-signer.key")
+	require.NoError(t, err, "could not open key file")
+	pemBytes, err := ioutil.ReadAll(keyReader)
```
Comment (cyli) [inline trustpinning/certs_test.go]: Non-blocking nit:  The open + `ioutil.ReadAll` could also be replaced with `ioutil.ReadFile`.

File: trustpinning/certs_test.go [hunk 4]
```diff
@@ -781,6 +781,200 @@ func testValidateRootRotationMissingNewSig(t *testing.T, keyAlg, rootKeyType str
 	require.Error(t, err, "insuficient signatures on root")
 }
 
+// TestValidateRootRotationTrustPinning runs a full root certificate rotation but ensures that
+// the specified trust pinning is respected with the new root for the Certs and TOFUs settings
+func TestValidateRootRotationTrustPinning(t *testing.T) {
```
Comment (cyli) [inline trustpinning/certs_test.go]: Yay thanks for these awesome tests!

File: trustpinning/trustpin.go (hunk 1 above)
Comment (riyazdf) [inline trustpinning/trustpin.go]: Sounds good, I'll combine them into a `!trustPinConfig.DisableTOFU || !firstBootstrap` case

**Comment by cyli** [comment]
LGTM!  Thanks for making sure the new roots conform to trust pinning too!

File: trustpinning/trustpin.go [hunk 5]
```diff
@@ -62,11 +62,13 @@ func NewTrustPinChecker(trustPinConfig TrustPinConfig, gun string) (CertChecker,
 		return t.caCheck, nil
 	}
 
-	if !trustPinConfig.DisableTOFU {
-		logrus.Debugf("trust-pinning: using TOFU")
+	// If TOFUs is not disabled or we already have previous trusted root data for this GUN (even with TOFUs disabled),
+	// use TOFUs.  It's ok if we have previous root data with TOFUs disabled because we've already
+	// bootstrapped the first use of trust
+	if !trustPinConfig.DisableTOFU || !firstBootstrap {
```
Comment (endophage) [inline trustpinning/trustpin.go]: Let's apply De Morgan's and invert the check so we have:

```
if DisableTOFU && firstBootstrap {
    return error
}
return tofusCheck
```

**Comment by endophage** [comment]
After one comment, looks great! First person to check in after CI passes should merge 👍
