### PR TITLE
Do not save old root roles until the first root rotation

### LINKED ISSUE #722: Delay saving of root roles
#648 started saving versions of the root role so that when the root is rotated, a previous role is saved along with the version.

Right now, when we sign the root, we see if the current root version has been saved and if not, we save it so in the future, root rotations will have a previous version to compare against.

This breaks against older versions of notary though that still have the keyDB (for instance against notary 0.2 and docker 1.10.3).

We should wait to save the previous role until we actually do a root rotation (which will still cause breakages with older versions of notary and docker, but will only do so if a root rotation is required).

### LINKED ISSUE #723: Trust delegation results in error on subsequent Docker Content Trust push to same repo:  "tuf: invalid role root.2."
Using Docker version 1.10.2, build c3959b1
Notary server and client both built from commit 134bdbc

To reproduce:

* Push to a repo using Content Trust
* Add trust delegation, following the instructions at http://docs.master.dockerproject.org/engine/security/trust/trust_delegation/
* Try to push again to the same repo from the same machine with Content Trust (it can be the same tag or a different tag)
* The push fails with an error: "Could not publish Repository: tuf: invalid role root.2."

In more detail:

1. Generate an SSL cert and import it into Notary:
**> openssl genrsa -out /root/delegation.key 2048**
**> openssl req -new -sha256 -key /root/delegation.key -out /root/delegation.csr -subj "/C=XX/ST=XX/L=XX/O=XX/OU=XX/CN=XX"**
**> openssl x509 -req -days 365 -in /root/delegation.csr -signkey /root/delegation.key -out /root/delegation.crt**
**> export NOTARY_DELEGATION_PASSPHRASE=notary_delegation_passphrase**
**> notary -d /root/.docker/trust key import /root/delegation.key --role targets/user**

2. Push using Content Trust:
**> export DOCKER_CONTENT_TRUST=1**
**> export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=targets**
**> export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE=root**
**> export DOCKER_CONTENT_TRUST_SERVER=https://notary-server:4443**
**> docker push registry-server:5000/a:v1**

3. Perform Content Trust Delegation, as specified at http://docs.master.dockerproject.org/engine/security/trust/trust_delegation/
**> export NOTARY_DELEGATION_PASSPHRASE=notary_delegation_passphrase**
**> export NOTARY_ROOT_PASSPHRASE=root**
**> export NOTARY_SNAPSHOT_PASSPHRASE=targets**
**> export NOTARY_TARGETS_PASSPHRASE=targets**
**> notary -s https://notary-server:4443 -d /root/.docker/trust key rotate registry-server:5000/a snapshot -r**
**> notary -s https://notary-server:4443 -d /root/.docker/trust delegation add registry-server:5000/a targets/releases /root/delegation.crt --all-paths**
**> notary -s https://notary-server:4443 -d /root/.docker/trust publish registry-server:5000/a**

4. Attempt to push the same ref from the same machine again, with Content Trust
**> export DOCKER_CONTENT_TRUST=1**
**> export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=targets**
**> export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE=root**
**> export DOCKER_CONTENT_TRUST_SERVER=https://notary-server:4443**
**> docker -D push registry-server:5000/a:v1**
> The push refers to a repository [registry-server:5000/a]
> [some output skipped]
> Signing and pushing trust metadata
> time="2016-05-06T02:40:03Z" level=debug msg="Adding cert with certID: 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=debug msg="Making dir path: /root/.docker/trust/tuf/registry-server:5000/a/changelist"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding target \"v1\" with sha256 \"3c846030a3d1e602db048edfbeb2cf5aa3aebf290375ed0b7a934297b8e6500a\" and size 920 bytes.\n"
> time="2016-05-06T02:40:03Z" level=debug msg="entered ValidateRoot with dns: registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="found the following root keys: [7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e]"
> time="2016-05-06T02:40:03Z" level=debug msg="found 1 valid leaf certificates for registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="found 1 valid root certificates for registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="entering root certificate rotation for: registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding cert with certID: 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=debug msg="ignoring certificate addition to: registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="Root validation succeeded for registry-server:5000/a"
> time="2016-05-06T02:40:03Z" level=debug msg="200 when retrieving metadata for root"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding key 09b98bb517115cddb819fb8fcd1b86ba39424740471a20ac2a49db577b93365b"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding key 1e56ba4ec24b5bf5967e175e629646b281574d1e320b126f32aae53a74e21eef"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding key 5b9c472858acb0a448bcb86b857ab52aae8d4f2e909d1e3b29ed574d407ac1fb"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding key 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding role root with keys 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=debug msg="Adding role root.2 with keys 7ddadbf013e88b4d83562286f0b33fca2385c711f9a95fad4f6be7397a51f72e"
> time="2016-05-06T02:40:03Z" level=error msg="Could not publish Repository: tuf: invalid role root.2."
tuf: invalid role root.2.

### PR DESCRIPTION
**Pull request by cyli**
Save both the previous root role and the current root role on root rotation, however.

Fixes #722 
Fixes #723 

However, Docker < 1.11 will still break as soon as a root rotation is done.

### CODE REVIEW

**Comment by cyli** [comment]
jenkins, test this please

File: tuf/tuf_test.go [hunk 1]
```diff
@@ -878,6 +873,20 @@ func TestReplaceBaseKeysInRoot(t *testing.T) {
...
+		_, err = repo.SignRoot(data.DefaultExpires(data.CanonicalRootRole))
+		require.NoError(t, err)
+
+		switch role {
+		case data.CanonicalRootRole:
+			// root role changed, so the old role and the new role should have been saved
+			require.Len(t, repo.Root.Signed.Roles, origNumRoles+2)
+		default:
+			// number of roles should not have changed
+			require.Len(t, repo.Root.Signed.Roles, origNumRoles)
```
Comment (riyazdf) [inline tuf/tuf_test.go]: 👍 thanks for adding this!

File: tuf/tuf_test.go [hunk 2]
```diff
@@ -111,17 +111,12 @@ func TestInitRepo(t *testing.T) {
...
-	savedRoot, err := repo.Root.BuildBaseRole("root.1")
-	require.Equal(t, "root.1", savedRoot.Name)
+	// after signing a new, there are only 4 roles: the 4 base roles
+	require.Len(t, repo.Root.Signed.Roles, 4)
 
-	// we can't compare the roots if the names are different
-	savedRoot.Name = data.CanonicalRootRole
-	require.NoError(t, err)
-	require.True(t, currRoot.Equals(savedRoot))
+	// can't use getBaseRole bcause it's not a valid real role
```
Comment (riyazdf) [inline tuf/tuf_test.go]: nit typo `because`

File: tuf/tuf_test.go [hunk 3]
```diff
@@ -111,17 +111,12 @@ func TestInitRepo(t *testing.T) {
 	ed25519 := signed.NewEd25519()
 	repo := initRepo(t, ed25519)
 	writeRepo(t, "/tmp/tufrepo", repo)
-	// after signing a new repo, the first version's root is saved
-	currRoot, err := repo.GetBaseRole(data.CanonicalRootRole)
-	require.NoError(t, err)
-	// can't use getBaseRole bcause it's not a valid real role
-	savedRoot, err := repo.Root.BuildBaseRole("root.1")
-	require.Equal(t, "root.1", savedRoot.Name)
+	// after signing a new, there are only 4 roles: the 4 base roles
```
Comment (riyazdf) [inline tuf/tuf_test.go]: nit: seems like we're missing `repo` after `new`

File: tuf/tuf.go [hunk 4]
```diff
@@ -845,28 +845,31 @@ func (tr *Repo) SignRoot(expires time.Time) (*data.Signed, error) {
...
 
-	// if the current role doesn't match with the latest saved role, save it
-	if !currRoot.Equals(latestSavedRole) {
-		rolesToSignWith = append(rolesToSignWith, currRoot)
+	// if the root role (root keys or root threshold) has changed, save the
+	// current  role if it hasn't already been saved, as well as saving the
+	// new root role
+	if !tr.originalRootRole.Equals(currRoot) {
+		// if the current role has not been saved before, save it now as
+		// role name "root.<previous version>"
```
Comment (endophage) [inline tuf/tuf.go]: With the piece of code below to always save the new role, this basically becomes a special case for the initial root role. Would it make sense to remove the below code and just use this piece to always save a root role when it's rotated out? That will also give a consistent meaning to the `<version>`, i.e. it will always be the last version for which that root role was current.

Comment (cyli) [inline tuf/tuf.go]: That makes sense

**Comment by endophage** [comment]
LGTM

File: tuf/tuf.go [hunk 5]
```diff
@@ -845,28 +845,23 @@ func (tr *Repo) SignRoot(expires time.Time) (*data.Signed, error) {
 		}
 	}
 
-	// if the root role has changed and original role had not been saved as a previous role, save it now
+	// If the root role (root keys or root threshold) has changed, save the
+	// previous role under the role name "root.version", such that the
+	// version number is always the latest version for which the that root role
+	// was valid. Also, guard against re-saving the prevoius role if the latest
```
Comment (riyazdf) [inline tuf/tuf.go]: nit typo: `prevoius`

File: tuf/tuf.go [hunk 6]
```diff
@@ -845,28 +845,23 @@ func (tr *Repo) SignRoot(expires time.Time) (*data.Signed, error) {
...
 	tempRoot.Signed.Version++
-
-	// if the current role doesn't match with the latest saved role, save it
-	if !currRoot.Equals(latestSavedRole) {
-		rolesToSignWith = append(rolesToSignWith, currRoot)
-
-		versionName := oldRootVersionName(tempRoot.Signed.Version)
-		tempRoot.Signed.Roles[versionName] = &data.RootRole{
-			KeyIDs: currRoot.ListKeyIDs(), Threshold: currRoot.Threshold}
-	}
```
Comment (riyazdf) [inline tuf/tuf.go]: this is really clean \o/

**Comment by riyazdf** [comment]
LGTM!

**Comment by cyli** [comment]
jenkins, test this please
