### PR TITLE
made fix as per open issue 310

### LINKED ISSUE #310: Suspect logic in trustmanager.GetPasswdDecryptBytes
Just a low-priority drive-by note while working on something else:

* After the cycle, `retErr` will always be nil, so it is currently useless.
* The `attempts` check should happen either before prompting for a passphrase, or after trying to use it (in fact, probably in the loop condition). The current way, prompting for a passphrase, ignoring it, and failing, does not make sense.

### PR DESCRIPTION
**Pull request by avaid96**
closes #310 
Signed-off-by: Avi Vaid <avaid1996@gmail.com>

### CODE REVIEW

File: trustmanager/keystore.go [hunk 1]
```diff
@@ -328,26 +327,22 @@ func GetPasswdDecryptBytes(passphraseRetriever notary.PassRetriever, pemBytes []
 			err    error
 		)
 		passwd, giveup, err = passphraseRetriever(name, alias, false, attempts)
+		if attempts > 10 {
```
Comment (riyazdf) [inline trustmanager/keystore.go]: Should this check go before we call `passphraseRetriever`, since we've determined that we have tried enough times and don't actually use `passwd`?

File: trustmanager/keystore.go [hunk 2]
```diff
@@ -328,26 +327,22 @@ func GetPasswdDecryptBytes(passphraseRetriever notary.PassRetriever, pemBytes []
...
 		}
-		if attempts > 10 {
-			return nil, "", ErrAttemptsExceeded{}
-		}
 
 		// Try to convert PEM encoded bytes back to a PrivateKey using the passphrase
 		privKey, err = utils.ParsePEMPrivateKey(pemBytes, passwd)
 		if err != nil {
-			retErr = ErrPasswordInvalid{}
+			logrus.Info(ErrPasswordInvalid{})
```
Comment (riyazdf) [inline trustmanager/keystore.go]: I'm fine with removing this log and just having these lines simplified to:

```
if err == nil {
    // We managed to parse the PrivateKey. We've succeeded!
    break
}
```

File: trustmanager/keystore.go [hunk 3]
```diff
@@ -319,35 +319,28 @@ func getSubdir(alias string) string {
...
-		if err != nil {
-			retErr = ErrPasswordInvalid{}
-		} else {
+		if err == nil {
 			// We managed to parse the PrivateKey. We've succeeded!
-			retErr = nil
 			break
 		}
 	}
-	if retErr != nil {
```
Comment (cyli) [inline trustmanager/keystore.go]: We might want to check if privKey is null here, and if so, return some kind of error.  Alternately, in line 339, do `privKey, retErr = ...` and leave this check here.

It's possible for us to never have decrypted the private key because `utils.ParsePEMPrivateKey` could have failed over and over.

Comment (avaid96) [inline trustmanager/keystore.go]: since we only exit the loop to reach this part if the error is nil and if it isn't then we will end up returning with ErrAttemptsExceeded or ErrPasswordInvalid, I thought this check was unnecessary and not hitting this part. So the retErr should always be nil over here. Am I missing a case?

Comment (cyli) [inline trustmanager/keystore.go]: Ah my bad yes, sorry, we are not checking the attempts as part of the for loop condition, just inside the for loop itself, so I got confused.  Thanks!

Comment (avaid96) [inline trustmanager/keystore.go]: perfect, thanks for the super quick review 😃

**Comment by cyli** [comment]
Thanks for fixing this @avaid96!  LGTM pending CI!

**Comment by riyazdf** [comment]
jenkins, test this please.

**Comment by riyazdf** [comment]
LGTM pending CI!

**Comment by riyazdf** [comment]
jenkins, ok to test.
