### PR TITLE
Passphrase fixups

### LINKED ISSUE #812: Passphrase attempt and errorring logic for keys could be improved
I was doing some local testing when I realized that it's possible to fail `> attempts` times on passphrases that are too short, but then notary will fail with `ErrAttemptsExceeded` after inputting a valid passphrase.  While most users may not run into this exact failure case, I think we could revisit and improve the passphrase attempt logic UX at the KeyStore level in general

```
🐳 $ bin/notary init repo
Root key found, using: 4327a8deba2cae19a4b393d2c6cf3a2f349652c84bc41bc1e09ade182d86b19a
Enter passphrase for root key with ID 4327a8d:
Enter passphrase for new targets key with ID f511f86 (repo):
Passphrase is too short. Please use a password manager to generate and store a good random passphrase.
Enter passphrase for new targets key with ID f511f86 (repo):
Passphrase is too short. Please use a password manager to generate and store a good random 
...
[truncated]
...
Enter passphrase for new targets key with ID f511f86 (repo):
Passphrase is too short. Please use a password manager to generate and store a good random passphrase.
Enter passphrase for new targets key with ID f511f86 (repo):
Repeat passphrase for new targets key with ID f511f86 (repo):

* fatal: failed to add key to filestore: maximum number of passphrase attempts exceeded
```

### LINKED ISSUE #899: When running in CI system (no TTY) give up on passphrase
When running in a CI system where no TTY is attached, if something goes wrong, notary winds up asking for a root pass phrase over and over without end.  We recently had our CI system run out of disk space due to gig's of logs with the repeating pattern:

```
Enter passphrase for new root key with ID fdd4003: 
Enter passphrase for new root key with ID fdd4003: 
Enter passphrase for new root key with ID fdd4003: 
```

Notary should be smarter and give up asking for a passphrase when there's no tty instead of looping.

### PR DESCRIPTION
**Pull request by riyazdf**
Fixes some logic in the keystore when counting number of passphrase attempts, especially when short passphrases are provided.

```
🐳 $ bin/notary init testGun
Root key found, using: 4327a8deba2cae19a4b393d2c6cf3a2f349652c84bc41bc1e09ade182d86b19a
Enter passphrase for root key with ID 4327a8d:
Enter passphrase for new targets key with ID 454c204 (testGun):
Passphrase is too short. Please use a password manager to generate and store a good random passphrase.
Enter passphrase for new targets key with ID 454c204 (testGun):
Passphrase is too short. Please use a password manager to generate and store a good random passphrase.
...
Enter passphrase for new targets key with ID 454c204 (testGun):
Passphrase is too short. Please use a password manager to generate and store a good random passphrase.

* fatal: failed to add key to filestore: maximum number of passphrase attempts exceeded
```

Also, ensures that `PromptRetriever()` has an actual terminal when requesting passphrases and will error out with `ErrNoInput` if that is not the case instead of trying to read input over and over.

Closes #899 
Closes #812

### CODE REVIEW

File: trustmanager/keystore.go [hunk 1]
```diff
@@ -142,13 +142,12 @@ func (s *GenericKeyStore) AddKey(keyInfo KeyInfo, privKey data.PrivateKey) error
 	name := filepath.Join(keyInfo.Gun, privKey.ID())
 	for attempts := 0; ; attempts++ {
 		chosenPassphrase, giveup, err = s.PassRetriever(name, keyInfo.Role, true, attempts)
-		if err != nil {
-			continue
+		if err == nil {
+			break
 		}
 		if giveup || attempts > 10 {
```
Comment (cyli) [inline trustmanager/keystore.go]: Non-blocking:  wondering if we should decrease this number to 3 or some such?  That would give the user 5 tries.  (currently it fails out after 12 tries - I was wondering whether that's too many)

**Comment by cyli** [comment]
Thank you for fixing this!  LGTM - took it for a spin and it correctly terminates, and in a script without stdin it immediately fails.

File: passphrase/passphrase.go [hunk 2]
```diff
@@ -85,13 +95,13 @@ func (br *boundRetriever) requestPassphrase(keyName, alias string, createNew boo
...
-	if term.IsTerminal(0) {
-		state, err := term.SaveState(0)
+	if term.IsTerminal(os.Stdin.Fd()) {
+		state, err := term.SaveState(os.Stdin.Fd())
 		if err != nil {
 			return "", false, err
 		}
-		term.DisableEcho(0, state)
-		defer term.RestoreTerminal(0, state)
+		term.DisableEcho(os.Stdin.Fd(), state)
```
Comment (endophage) [inline passphrase/passphrase.go]: Yeah, this is a good reason for us to switch to crypto/terminal in the future. Better API for retrieving passwords from the terminal.

File: trustmanager/keystore.go (hunk 1 above)
Comment (endophage) [inline trustmanager/keystore.go]: I agree. 10 is feeling like too many. Also would be good to move the exact number to a const.

**Comment by endophage** [comment]
LGTM. We can modify the number of retries separately
